### ISSUE TITLE
Copy ibt after process

### ISSUE THREAD

**Issue by a1ad** [patrickmoore/Mu#20]
Hi,

I would like to have a config setting to auto copy the ibt file to a different location after processing instead of removing the file.

Greets and thanks for Mu!

edit: is there a reason why Mu is not opensource?

**Comment by MerlinCooper** [comment]
> 
> 
> Hi,
> 
> I would like to have a config setting to auto copy the ibt file to a different location after processing instead of removing the file.
> 
If the target you are trying to achieve is that you store the ibt and ld files in a different directory you could just use another target directory for the generated ld-files. 

 
> edit: is there a reason why Mu is not opensource?

To my understanding it is not open source because of the licensing model for the API from MoTec used to generate the MoTec Data format. Even when the source code would be available you would have to license that on an annual basis. 

https://www.motec.com.au/i2/i2licences/

**Comment by a1ad** [comment]
I want to move the ibt files to a archive disk.

**Comment by MerlinCooper** [comment]
> 
> 
> I want to move the ibt files to a archive disk.

If you are just trying to free up space on the hard-driver where iRacing is installed you could do that by using a symbolic link. That's at least how I managed to have the ibt-files stored in a different (larger) drive then were iRacing is installed (on my M2 drive). 

To create that just follow the following steps:

a) Move the Telemetry folder in your iRacing Folder to the hard-drive were you want to store/archive the ibt-files. 
b) Open a Command prompt. Change into the iRacing folder and type (assuming that you copied the telemetry folder onto your d-drive root directory. 
`mklink /J Telemetry d:\Telemetry`

If you use another drive / folder just change the last part accordingly.

**Comment by a1ad** [comment]
What? Windows has symbolic links! Mind blown. Yes that is a great alternative. Ill try it tomorrow. 

Thanks

**Comment by a1ad** [comment]
Symbolic link is a perfect solution. Thanks
